name: Test Workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
